#-----------------------------------------------------------------------------------------------------------------------
# All example patches and configurations are listed here.
#-----------------------------------------------------------------------------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace where spinnaker and all its infrastructure will be installed.
# NOTE: If changed, also change it in all ClusterRoleBinding namespace references.
namespace: spinnaker

resources:
  - spinnakerservice.yml               # (Mandatory). Base spinnaker manifest
  - infrastructure/minio.yml           # (Optional, not for production use). S3 compatible data store
  - infrastructure/mysql.yml           # (Optional, not for production use). MySQL server needed if using SQL backend in Spinnaker
#  - infrastructure/opa.yml             # (Optional). OPA server for using with Armory's policy engine, for enforcing pipeline policies
#  - infrastructure/debugging-tools.yml # (Optional). A pod with some tools for troubleshooting spinnaker (curl, kubectl, vault, etc.)
  - accounts/kubernetes/spin-sa.yml    # (Optional, needed by accounts/kubernetes/patch-kube.yml). Kubernetes service account for spinnaker to use in its own cluster
#  - expose/ingress-nginx.yml          # (Optional). Spinnaker ingress definition
#  - expose/spin-gate-expose.yml       # (Optional). Alternate service definition for gate for exposing spinnaker with maximum configurability
#  - expose/spin-deck-expose.yml       # (Optional). Alternate service definition for deck for exposing spinnaker with maximum configurability

#bases:
#  - infrastructure/prometheus-grafana  # (Optional). Used in conjunction with monitoring/patch-prometheus.yml for monitoring spinnaker

patchesStrategicMerge:
  # Spinnaker persistence
  - persistence/patch-minio.yml
#  - persistence/patch-s3.yml
  - persistence/patch-sql-clouddriver.yml          ## setup clouddriver to use SQL for storage
  - persistence/patch-sql-front50.yml              ## setup front50 to use SQL for storage
  - persistence/patch-sql-orca.yml                 ## setup orca to use SQL for storage
#  - persistence/patch-redis.yml

  # Automatically expose spinnaker
  - expose/patch-lb.yml
#  - expose/patch-lb-aws.yml
#  - expose/patch-nodeport.yml
#  - expose/patch-ingress.yml
#  - expose/patch-urls.yml

  # Authentication and authorization
#  - security/patch-github.yml
#  - security/patch-saml.yml
#  - security/patch-file-authz.yml

  # Kubernetes accounts
  - accounts/kubernetes/patch-kube.yml
#  - accounts/kubernetes/patch-dynamic-git.yml
#  - accounts/kubernetes/patch-dynamic-vault.yml

  # AWS accounts
#  - accounts/aws/patch-aws.yml
#  - accounts/aws/packer-templates.yml

  # Artifact accounts
  - accounts/docker/patch-dockerhub.yml
#  - accounts/docker/patch-gcr.yml
#  - accounts/git/patch-github.yml
#  - accounts/git/patch-gitrepo.yml
#  - accounts/git/patch-gitlab.yml
#  - accounts/git/patch-bitbucket.yml
#  - accounts/s3/patch-s3.yml
#  - accounts/gcs/patch-gcs.yml
#  - accounts/http/patch-http.yml

  # Armory features
#  - armory/patch-terraformer.yml
#  - armory/patch-dinghy.yml
#  - armory/patch-diagnostics.yml
#  - armory/patch-policyengine.yml  # Requires spin-policies configmap

  # Spinnaker monitoring
#  - accounts/prometheus/patch-prometheus.yml
#  - accounts/datadog/patch-datadog.yml

  # Customizations to spinnaker pods in Kubernetes
#  - spinnaker_deployment/patch-volumes.yml
#  - spinnaker_deployment/patch-sizing.yml
#  - spinnaker_deployment/patch-labels-annotations.yml
#  - spinnaker_deployment/patch-debug-jvm.yml

  # Plugins
#  - plugins/patch-plugin-wait.yml

# Mounting any custom files into spinnaker pods (see patch-volumes.yml)
#generatorOptions:
#  disableNameSuffixHash: true
#secretGenerator:
#  - name: custom-volume
#    files:
#      - spinnaker_deployment/custom-volume/file.txt

#configMapGenerator:
#  # ConfigMap holding OPA policy definitions to use by Armory's policy engine. Required by patch-policyengine.yml
#  - name: spin-policies
#    files:
#      - armory/policies/manual-judgement.rego
